# Configuration for the Rust GGEZ Shapes App

[window]
width = 1024.0
height = 768.0
title = "My Configured Shapes App!"

[shape]
width = 120.0
height = 70.0
corner_radius = 15.0
color_r = 255
color_g = 105
color_b = 180

# Optional: Customize the selection outline
# If these are omitted, the application uses internal defaults (Yellow, 2.0 width)
selection_outline_color_r = 0     # Example: Green R
selection_outline_color_g = 255   # Example: Green G
selection_outline_color_b = 0     # Example: Green B
selection_outline_width = 3.0     # Example: Thicker outline

