# Configuration for the Rust GGEZ Circles App

[window]
width = 1530.0
height = 1024.0
title = "My Configured Circles App!"

[shape]
width = 200.0
height = 60.0
corner_radius = 10.0
color_r = 100
color_g = 200
color_b = 255

