# Configuration for the Rust GGEZ Shapes App

[window]
width = 1024.0
height = 768.0
title = "vrun"
msaa_level = 4 # Optional: Anti-aliasing samples. Use 1 (off) or 4 (on). Defaults to 4 if omitted or invalid.
ui_scale_factor = 2.0 # Optional: Make UI elements appear larger, use for high dpi screens like Apple Retna

[shape]
width = 120.0
height = 70.0
corner_radius = 15.0
color_r = 255
color_g = 105
color_b = 180

# Optional: Customize the selection outline
# If these are omitted, the application uses internal defaults (Yellow, 2.0 width)
selection_outline_color_r = 150     # Example: Green R
selection_outline_color_g = 140   # Example: Green G
selection_outline_color_b = 140     # Example: Green B
selection_outline_width = 3.0     # Example: Thicker outline

